name: Generate Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: amaan-usmani
          template: classic
          base: header, activity, community, repositories
          config_animations: true
          config_timezone: Asia/Kolkata
          filename: metrics.svg

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update metrics image"
          file_pattern: metrics.svg
