name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: amaan-usmani
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Push output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          file_pattern: "dist/*"
